### ISSUE TITLE
bf-Screen overflow

### ISSUE THREAD

**Issue by surajsingla333** [buidl-labs/zombies-in-the-room#30]
-  **System Information**

  - Mozilla Firefox v74.0
  - Windows 10 Enterprise

- **Describe the bug**
   Whenever we start typing something on the editor, the screen overflows and we see vertical and horizontal scrollbars. This issue is not encountered in the development run but only in deployment.

  

- **To Reproduce**

      1. Go to 'https://deploy-preview-25--blissful-mcnulty-82f253.netlify.com/lesson/chapter-01'
      2. Type something on the editor
      3. The screen will overflow'

-**Expected behavior**
       The screen should not overflow and it should completely fit in the browser screen.

**Comment by bhaskarSingh** [comment]
I am not able to reproduce the bug
**System Information**
- OS: Mac
- Browser: chrome
Possible to share loom link for it ?

**Comment by surajsingla333** [comment]
> 
> 
> I am not able to reproduce the bug
> **System Information**
> 
>     * OS: Mac
> 
>     * Browser: chrome
> 
> 
> Possible to share loom link for it ?

Here is the loom link : https://www.loom.com/share/dfa50340dea34703b58d62ce953d2704

**Comment by bhaskarSingh** [comment]
seems like the issue is with the firefox browser support, for `x` CSS feature: [different browser/viewport screenshots](https://front.comparium.app/?url=https://blissful-mcnulty-82f253.netlify.com/lesson/chapter-01&browser=WINDOWS_chrome_71.0_1024&browser=WINDOWS_firefox_68.0_1024&browser=WINDOWS_opera_58.0_1024&browser=OSX_safari_13.0_1024&browser=WINDOWS_chrome_71.0_768&browser=WINDOWS_firefox_68.0_768&browser=WINDOWS_opera_58.0_768&browser=OSX_safari_13.0_768&browser=WINDOWS_chrome_71.0_375&browser=WINDOWS_firefox_68.0_375&browser=WINDOWS_opera_58.0_375&browser=OSX_safari_13.0_375&browser=WINDOWS_chrome_71.0_1920&browser=WINDOWS_firefox_68.0_1920&browser=WINDOWS_opera_58.0_1920&browser=OSX_safari_13.0_1920)

**Comment by bhaskarSingh** [comment]
Possible solution: turning auto-complete suggestion off

**Comment by surajsingla333** [comment]
> 
> 
> seems like the issue is with the firefox browser support, for `x` CSS feature: [different browser/viewport screenshots](https://front.comparium.app/?url=https://blissful-mcnulty-82f253.netlify.com/lesson/chapter-01&browser=WINDOWS_chrome_71.0_1024&browser=WINDOWS_firefox_68.0_1024&browser=WINDOWS_opera_58.0_1024&browser=OSX_safari_13.0_1024&browser=WINDOWS_chrome_71.0_768&browser=WINDOWS_firefox_68.0_768&browser=WINDOWS_opera_58.0_768&browser=OSX_safari_13.0_768&browser=WINDOWS_chrome_71.0_375&browser=WINDOWS_firefox_68.0_375&browser=WINDOWS_opera_58.0_375&browser=OSX_safari_13.0_375&browser=WINDOWS_chrome_71.0_1920&browser=WINDOWS_firefox_68.0_1920&browser=WINDOWS_opera_58.0_1920&browser=OSX_safari_13.0_1920)

Let's ask Abhinav as well to test this.

**Comment by surajsingla333** [comment]
> 
> 
> Possible solution: turning auto-complete suggestion off

Got you!

**Comment by dhruv10** [comment]
Cannot replicate the issue on Mozilla Firefox v75.0

Is this solved @bhaskarSingh ?

**Comment by bhaskarSingh** [comment]
@dhruv10  yes
